plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'ai.kratos.tailcat'
version = '0.1.0'

android {
  namespace "ai.kratos.tailcat"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  compileOnly files(rootProject.file('../../../target/tailcat/KratosTailcat.aar'))
}
