MOBILE_TOOLS_ROOT="${HOME}/.local"

export GOROOT="$MOBILE_TOOLS_ROOT/go1.27.1/go"
export GOPATH="$MOBILE_TOOLS_ROOT/go"
export ANDROID_HOME="$MOBILE_TOOLS_ROOT/android-sdk"
export ANDROID_SDK_ROOT="$ANDROID_HOME"
export ANDROID_NDK_HOME="$ANDROID_HOME/ndk/28.0.13004108"
export PATH="$MOBILE_TOOLS_ROOT/node-v24/bin:$GOROOT/bin:$GOPATH/bin:$ANDROID_HOME/platform-tools:$PATH"
