[package]
name = "kratos-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kratos-proto.workspace = true
kratos-sync.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
kratos-doc.workspace = true
